"use client";

import AppShell from "@/components/AppShell";
import { api } from "@/lib/api";
import { Employee } from "@/lib/types";
import { Alert, Button, FormControlLabel, Grid2 as Grid, MenuItem, Paper, Switch, TextField, Typography } from "@mui/material";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

export default function CreateEmployeePage() {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError(""); const data = new FormData(event.currentTarget);
    const skillName = String(data.get("skillName") ?? "").trim();
    const body: Employee = { fullName: String(data.get("fullName")), position: String(data.get("position")), seniorityLevel: String(data.get("seniorityLevel")), mainTechStack: String(data.get("mainTechStack")), additionalSkills: String(data.get("additionalSkills")), capabilityDescription: String(data.get("capabilityDescription")), hourlyRate: Number(data.get("hourlyRate")), weeklyAvailableHours: Number(data.get("weeklyAvailableHours")), isAvailable: data.get("isAvailable") === "on", skills: skillName ? [{ skillName, knowledgeLevel: String(data.get("knowledgeLevel")), yearsOfExperience: Number(data.get("yearsOfExperience")) }] : [] };
    try { await api("/employees", { method: "POST", body: JSON.stringify(body) }); router.push("/admin/employees"); } catch (x) { setError(x instanceof Error ? x.message : "Could not create employee."); setBusy(false); }
  }
  return <AppShell role="Admin"><Typography variant="h4">Add employee</Typography><Typography color="text.secondary" mb={3}>Add the capabilities used for AI team recommendations.</Typography><Paper elevation={0} sx={{ p: { xs: 2, md: 4 }, border: "1px solid #e5e9f2" }}><Grid container spacing={2.5} component="form" onSubmit={submit}>{error && <Grid size={12}><Alert severity="error">{error}</Alert></Grid>}<Grid size={{ xs: 12, md: 6 }}><TextField fullWidth name="fullName" label="Full name" required /></Grid><Grid size={{ xs: 12, md: 6 }}><TextField fullWidth name="position" label="Position" required /></Grid><Grid size={{ xs: 12, md: 4 }}><TextField fullWidth select name="seniorityLevel" label="Seniority" defaultValue="Mid"><MenuItem value="Junior">Junior</MenuItem><MenuItem value="Mid">Mid</MenuItem><MenuItem value="Senior">Senior</MenuItem><MenuItem value="Lead">Lead</MenuItem></TextField></Grid><Grid size={{ xs: 12, md: 8 }}><TextField fullWidth name="mainTechStack" label="Main tech stack" required placeholder="ASP.NET Core, C#, SQL" /></Grid><Grid size={12}><TextField fullWidth name="additionalSkills" label="Additional skills" /></Grid><Grid size={12}><TextField fullWidth multiline minRows={3} name="capabilityDescription" label="Capability description" /></Grid><Grid size={{ xs: 12, md: 4 }}><TextField fullWidth name="hourlyRate" label="Hourly rate (€)" type="number" required slotProps={{ htmlInput: { min: 0, step: 1 } }} /></Grid><Grid size={{ xs: 12, md: 4 }}><TextField fullWidth name="weeklyAvailableHours" label="Available hours/week" type="number" required slotProps={{ htmlInput: { min: 0, max: 40 } }} /></Grid><Grid size={{ xs: 12, md: 4 }}><FormControlLabel control={<Switch name="isAvailable" defaultChecked />} label="Available for projects" sx={{ mt: 1 }} /></Grid><Grid size={12}><Typography variant="h6" mt={1}>Primary skill</Typography></Grid><Grid size={{ xs: 12, md: 5 }}><TextField fullWidth name="skillName" label="Skill name" placeholder="ASP.NET Core" /></Grid><Grid size={{ xs: 12, md: 4 }}><TextField fullWidth select name="knowledgeLevel" label="Knowledge level" defaultValue="Advanced"><MenuItem value="Beginner">Beginner</MenuItem><MenuItem value="Intermediate">Intermediate</MenuItem><MenuItem value="Advanced">Advanced</MenuItem><MenuItem value="Expert">Expert</MenuItem></TextField></Grid><Grid size={{ xs: 12, md: 3 }}><TextField fullWidth name="yearsOfExperience" label="Years experience" type="number" defaultValue={0} slotProps={{ htmlInput: { min: 0, step: 0.5 } }} /></Grid><Grid size={12}><Button type="submit" variant="contained" size="large" disabled={busy}>{busy ? "Saving…" : "Create employee"}</Button></Grid></Grid></Paper></AppShell>;
}
